# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('endereco', models.TextField()),
                ('bairro', models.CharField(max_length=64)),
                ('cidade', models.CharField(max_length=64)),
                ('estado', models.CharField(max_length=64)),
                ('pais', models.CharField(max_length=64)),
                ('atributos', models.ManyToManyField(to='lugares.Atributo')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('texto', models.TextField()),
                ('avaliacao', models.CharField(choices=[('pessimo', 'P\xe9ssimo'), ('ruim', 'Ruim'), ('regular', 'Regular'), ('bom', 'Bom'), ('otimo', '\xd3timo')], default='regular', max_length=64)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lugares.Local')),
            ],
        ),
    ]
