# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='atributos',
            field=models.ManyToManyField(blank=True, null=True, to='lugares.Atributo'),
        ),
    ]
