# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0002_auto_20160819_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('localRetratado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_local', to='lugares.Local')),
            ],
        ),
    ]
