# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 08:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lugares', '0004_auto_20160820_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.DateField(default=datetime.datetime(2016, 8, 20, 8, 34, 31, 931974, tzinfo=utc), verbose_name='dataInicio')),
                ('horaFim', models.DateField(default=datetime.datetime(2016, 8, 20, 8, 34, 31, 932012, tzinfo=utc), verbose_name='dataFim')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imovel_locado', to=settings.AUTH_USER_MODEL)),
                ('localLocacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locacao', to='lugares.Local')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imovel_alugado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
