# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 11:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0005_locacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locacao',
            name='horaFim',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='horaInicio',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='locador',
        ),
        migrations.AddField(
            model_name='locacao',
            name='dataDaLocacao',
            field=models.DateField(default=datetime.datetime(2016, 8, 20, 11, 8, 54, 540682, tzinfo=utc), verbose_name='dataInicio'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='locatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imovel_aluc', to=settings.AUTH_USER_MODEL),
        ),
    ]
