# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0006_auto_20160820_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='dataDaLocacao',
            field=models.DateField(default=datetime.datetime(2016, 8, 20, 11, 20, 19, 594653, tzinfo=utc), verbose_name='dataInicio'),
        ),
    ]
